feat: `mix deps.update ex_aws`
Still fixing dependency compile issues

```
==> ex_aws
Compiling 27 files (.ex)

== Compilation error in file lib/ex_aws/config/defaults.ex ==
** (ArgumentError) cannot inject attribute @partitions into function/macro because cannot escape #Reference<0.3572891366.832962565.167595>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.18.4) lib/kernel.ex:3777: Kernel.do_at_escape/2
    (elixir 1.18.4) expanding macro: Kernel.@/1
    lib/ex_aws/config/defaults.ex:100: ExAws.Config.Defaults.host/2
could not compile dependency :ex_aws, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_aws --force", update it with "mix deps.update ex_aws" or clean it with "mix deps.clean ex_aws"
```