feat: update dialyxir `1.1.0` => `1.4`
Trying to solve dialyxir error

```
** (FunctionClauseError) no function clause matching in :erl_types.from_form/5
    (dialyzer 5.4) erl_types.erl:4054: :erl_types.from_form({:type, {485, 45}, :fun, [{:remote_type, {485, 63}, [{:atom, 0, Ecto.Queryable}, {:atom, 0, :t}, []]}]}, {:from_form, {:spec, {Ecto.Multi, :all, 4}, ~c"lib/ecto/multi.ex"}, #Reference<0.1225511893.2969698305.100801>, #Reference<0.1225511893.2969698305.100800>, %{}, []}, 16, 9685, {:cache, %{{Ecto.Multi, :merge, 12, [], [type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :union, [:none, :none, {:c, :function, {{:c, :product, [{:c, :map, {[], :any, :any}, :unknown}], :unknown}, {:c, :map, {[{{:c, :atom, [:__struct__], :unknown}, :mandatory, {:c, :atom, [Ecto.Multi], :unknown}}, {{:c, :atom, [:names], :unknown}, :mandatory, {:c, :map, {[], :any, :any}, :unknown}}, {{:c, :atom, [:operations], :unknown}, :mandatory, {:c, :list, {{:c, :tuple, [:any, :any], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}}], :any, :any}, :unknown}}, :unknown}, :none, :none, :none, {:c, :tuple, [{:c, :atom, :any, :unknown}, {:c, :atom, :any, :unknown}, {:c, :list, {:any, {:c, nil, [], :unknown}}, :unknown}], {3, :any}}, :none], :unknown}, 4}, {Keyword, :value, 9, [], [type: {Keyword, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {:any, 0}, {Ecto.Repo, :t, 12, [], [type: {Ecto.Multi, :run, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :atom, :any, :unknown}, 0}, {Ecto.Schema, :schema, 12, [], [type: {Ecto.Schema, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :map, {[], {:c, :atom, :any, :unknown}, :any}, :unknown}, 15}, {:sets, :seg, 14, [], [record: :set, type: {:sets, :set, 1}, type: {MapSet, :internal, 1}, type: {MapSet, :t, 1}, type: {MapSet, :t, 0}, type: {Ecto.Multi, :names, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :tuple, :any, {:any, :any}}, 0}, {String, :t, 10, [], [type: {Ecto.Schema, :prefix, 0}, type: {Ecto.Schema.Metadata, :t, 1}, type: {Ecto.Schema.Metadata, :t, 0}, type: {Ecto.Schema, :schema, 0}, type: {Ecto.Schema, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :binary, {8, 0}, :unknown}, 0}, {Ecto.Query, :t, 12, [], [type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :map, {[{{:c, :atom, [:__struct__], :unknown}, :mandatory, {:c, :atom, [Ecto.Query], :unknown}}, {{:c, :atom, [:aliases], :unknown}, :mandatory, :any}, {{:c, :atom, [:assocs], :unknown}, :mandatory, :any}, {{:c, :atom, [:combinations], :unknown}, :mandatory, :any}, {{:c, :atom, [:distinct], :unknown}, :mandatory, :any}, {{:c, :atom, [:from], :unknown}, :mandatory, :any}, {{:c, :atom, [:group_bys], :unknown}, :mandatory, :any}, {{:c, :atom, [:havings], :unknown}, :mandatory, :any}, {{:c, :atom, [:joins], :unknown}, :mandatory, :any}, {{:c, :atom, [:limit], :unknown}, :mandatory, :any}, {{:c, :atom, [:lock], :unknown}, :mandatory, :any}, {{:c, :atom, [:offset], :unknown}, :mandatory, :any}, {{:c, :atom, [:order_bys], :unknown}, :mandatory, :any}, {{:c, :atom, [:prefix], :unknown}, :mandatory, :any}, {{:c, :atom, [:preloads], :unknown}, :mandatory, :any}, {{:c, :atom, [:select], :unknown}, :mandatory, :any}, {{:c, :atom, [:sources], :unknown}, :mandatory, :any}, {{:c, :atom, [:updates], :unknown}, :mandatory, :any}, {{:c, :atom, [:wheres], :unknown}, :mandatory, :any}, {{:c, :atom, [:windows], :unknown}, :mandatory, :any}, {{:c, :atom, [:with_ctes], :unknown}, :mandatory, :any}], :none, :none}, :unknown}, 21}, {Ecto.Schema.Metadata, :context, 10, [], [type: {Ecto.Schema.Metadata, :t, 1}, type: {Ecto.Schema.Metadata, :t, 0}, type: {Ecto.Schema, :schema, 0}, type: {Ecto.Schema, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {:any, 0}, {Ecto.Changeset, :t, 2, [:any], [type: {Ecto.Changeset, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {:any, 0}, {Ecto.Multi, :operation, 13, [], [type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :tuple_set, [{2, [{:c, :tuple, [{:c, :atom, [:inspect], :unknown}, {:c, :list, {{:c, :tuple, [{:c, :atom, :any, :unknown}, :any], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}], {2, {:c, :atom, [:inspect], :unknown}}}, {:c, :tuple, [{:c, :atom, [:merge], :unknown}, {:c, :union, [:none, :none, {:c, :function, {{:c, :product, [{:c, :map, {[], :any, :any}, :unknown}], :unknown}, {:c, :map, {[{{:c, :atom, [:__struct__], :unknown}, :mandatory, {:c, :atom, [Ecto.Multi], :unknown}}, {{:c, :atom, [:names], :unknown}, :mandatory, {:c, :map, {[], ...}, :unknown}}, {{:c, :atom, [:operations], :unknown}, :mandatory, {:c, :list, {...}, ...}}], :any, :any}, :unknown}}, :unknown}, :none, :none, :none, {:c, :tuple, [{:c, :atom, :any, :unknown}, {:c, :atom, :any, :unknown}, {:c, :list, {:any, {:c, nil, [], ...}}, :unknown}], {3, :any}}, :none], :unknown}], {2, {:c, :atom, [:merge], :unknown}}}, {:c, :tuple, [{:c, :atom, [:put], :unknown}, :any], {2, {:c, :atom, [:put], :unknown}}}, {:c, :tuple, [{:c, :atom, [:run], :unknown}, {:c, :function, {{:c, :product, [{:c, :atom, :any, :unknown}, {:c, :map, {[], :any, :any}, :unknown}], :unknown}, {:c, :tuple_set, [{2, [{:c, :tuple, [{:c, :atom, [:error], :unknown}, :any], {2, {:c, :atom, [:error], :unknown}}}, {:c, :tuple, [{:c, :atom, [:ok], :unknown}, :any], {2, {:c, :atom, [...], ...}}}]}], :unknown}}, :unknown}], {2, {:c, :atom, [:run], :unknown}}}]}, {3, [{:c, :tuple, [{:c, :atom, [:changeset], :unknown}, {:c, :map, {[{{:c, :atom, [:__struct__], :unknown}, :mandatory, {:c, :atom, [Ecto.Changeset], :unknown}}, {{:c, :atom, [:action], :unknown}, :mandatory, {:c, :atom, :any, :unknown}}, {{:c, :atom, [:changes], :unknown}, :mandatory, {:c, :map, {[], {:c, :atom, :any, :unknown}, :any}, :unknown}}, {{:c, :atom, [:constraints], :unknown}, :mandatory, {:c, :list, {{:c, :map, {[{{:c, :atom, [...], ...}, :mandatory, {:c, ...}}, {{:c, :atom, ...}, :mandatory, {...}}, {{:c, ...}, :mandatory, ...}, {{...}, ...}, {...}, ...], :none, :none}, :unknown}, {:c, nil, [], :unknown}}, :unknown}}, {{:c, :atom, [:data], :unknown}, :mandatory, {:c, :union, [{:c, :atom, [nil], :unknown}, :none, :none, :none, :none, :none, :none, {:c, ...}], :unknown}}, {{:c, :atom, [:empty_values], :unknown}, :mandatory, :any}, {{:c, :atom, [:errors], :unknown}, :mandatory, {:c, :list, {{:c, :tuple, [{:c, :atom, ...}, {:c, ...}], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}}, {{:c, :atom, [:filters], :unknown}, :mandatory, {:c, :map, {[], {:c, :atom, :any, :unknown}, :any}, :unknown}}, {{:c, :atom, [:params], :unknown}, :mandatory, {:c, :union, [{:c, :atom, [nil], :unknown}, :none, :none, :none, :none, ...], :unknown}}, {{:c, :atom, [:prepare], :unknown}, :mandatory, {:c, :list, {{:c, :function, {...}, ...}, {:c, nil, ...}}, :unknown}}, {{:c, :atom, [:repo], :unknown}, :mandatory, {:c, :atom, :any, :unknown}}, {{:c, :atom, [:repo_opts], :unknown}, :mandatory, {:c, :list, {{:c, ...}, {...}}, :unknown}}, {{:c, :atom, [:required], :unknown}, :mandatory, {:c, :list, {{...}, ...}, :unknown}}, {{:c, :atom, [:types], :unknown}, :mandatory, {:c, :union, [...], ...}}, {{:c, :atom, [:valid?], :unknown}, :mandatory, {:c, :atom, ...}}, {{:c, :atom, [...], ...}, :mandatory, {:c, ...}}], :none, :none}, :unknown}, {:c, :list, {{:c, :tuple, [{:c, :atom, :any, :unknown}, :any], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}], {3, {:c, :atom, [:changeset], :unknown}}}, {:c, :tuple, [{:c, :atom, [:delete_all], :unknown}, {:c, :map, {[{{:c, :atom, [ (truncated)

Error: 02:28:32.450 [error] Process #PID<0.47130.0> raised an exception
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 7.0.2) :ets.lookup(#Reference<0.1225511893.2969698305.100808>, :inet_epmd_tls_socket)
    (dialyzer 5.4) dialyzer_codeserver.erl:394: :dialyzer_codeserver.get_temp_contracts/2
    (dialyzer 5.4) dialyzer_contracts.erl:209: :dialyzer_contracts.process_contract_remote_types_module/2
    (dialyzer 5.4) dialyzer_worker.erl:80: :dialyzer_worker.run/1

Error: 02:28:32.491 [error] Process #PID<0.43228.0> raised an exception
** (FunctionClauseError) no function clause matching in :dialyzer_codeserver.get_callbacks/1
    (dialyzer 5.4) dialyzer_codeserver.erl:358: :dialyzer_codeserver.get_callbacks({:function_clause, [{:erl_types, :from_form, [{:type, {485, 45}, :fun, [{:remote_type, {485, 63}, [{:atom, 0, Ecto.Queryable}, {:atom, 0, :t}, []]}]}, {:from_form, {:spec, {Ecto.Multi, :all, 4}, ~c"lib/ecto/multi.ex"}, #Reference<0.1225511893.2969698305.100801>, #Reference<0.1225511893.2969698305.100800>, %{}, []}, 16, 9685, {:cache, %{{Ecto.Multi, :merge, 12, [], [type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :union, [:none, :none, {:c, :function, {{:c, :product, [{:c, :map, {[], :any, :any}, :unknown}], :unknown}, {:c, :map, {[{{:c, :atom, [:__struct__], :unknown}, :mandatory, {:c, :atom, [Ecto.Multi], :unknown}}, {{:c, :atom, [:names], :unknown}, :mandatory, {:c, :map, {[], :any, :any}, :unknown}}, {{:c, :atom, [:operations], :unknown}, :mandatory, {:c, :list, {{:c, :tuple, [:any, :any], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}}], :any, :any}, :unknown}}, :unknown}, :none, :none, :none, {:c, :tuple, [{:c, :atom, :any, :unknown}, {:c, :atom, :any, :unknown}, {:c, :list, {:any, {:c, nil, [], :unknown}}, :unknown}], {3, :any}}, :none], :unknown}, 4}, {Keyword, :value, 9, [], [type: {Keyword, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {:any, 0}, {Ecto.Repo, :t, 12, [], [type: {Ecto.Multi, :run, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :atom, :any, :unknown}, 0}, {Ecto.Schema, :schema, 12, [], [type: {Ecto.Schema, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :map, {[], {:c, :atom, :any, :unknown}, :any}, :unknown}, 15}, {:sets, :seg, 14, [], [record: :set, type: {:sets, :set, 1}, type: {MapSet, :internal, 1}, type: {MapSet, :t, 1}, type: {MapSet, :t, 0}, type: {Ecto.Multi, :names, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :tuple, :any, {:any, :any}}, 0}, {String, :t, 10, [], [type: {Ecto.Schema, :prefix, 0}, type: {Ecto.Schema.Metadata, :t, 1}, type: {Ecto.Schema.Metadata, :t, 0}, type: {Ecto.Schema, :schema, 0}, type: {Ecto.Schema, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :binary, {8, 0}, :unknown}, 0}, {Ecto.Query, :t, 12, [], [type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :map, {[{{:c, :atom, [:__struct__], :unknown}, :mandatory, {:c, :atom, [Ecto.Query], :unknown}}, {{:c, :atom, [:aliases], :unknown}, :mandatory, :any}, {{:c, :atom, [:assocs], :unknown}, :mandatory, :any}, {{:c, :atom, [:combinations], :unknown}, :mandatory, :any}, {{:c, :atom, [:distinct], :unknown}, :mandatory, :any}, {{:c, :atom, [:from], :unknown}, :mandatory, :any}, {{:c, :atom, [:group_bys], :unknown}, :mandatory, :any}, {{:c, :atom, [:havings], :unknown}, :mandatory, :any}, {{:c, :atom, [:joins], :unknown}, :mandatory, :any}, {{:c, :atom, [:limit], :unknown}, :mandatory, :any}, {{:c, :atom, [:lock], :unknown}, :mandatory, :any}, {{:c, :atom, [:offset], :unknown}, :mandatory, :any}, {{:c, :atom, [:order_bys], :unknown}, :mandatory, :any}, {{:c, :atom, [:prefix], :unknown}, :mandatory, :any}, {{:c, :atom, [:preloads], :unknown}, :mandatory, :any}, {{:c, :atom, [:select], :unknown}, :mandatory, :any}, {{:c, :atom, [:sources], :unknown}, :mandatory, :any}, {{:c, :atom, [:updates], :unknown}, :mandatory, :any}, {{:c, :atom, [:wheres], :unknown}, :mandatory, :any}, {{:c, :atom, [:windows], :unknown}, :mandatory, :any}, {{:c, :atom, [...], ...}, :mandatory, :any}], :none, :none}, :unknown}, 21}, {Ecto.Schema.Metadata, :context, 10, [], [type: {Ecto.Schema.Metadata, :t, 1}, type: {Ecto.Schema.Metadata, :t, 0}, type: {Ecto.Schema, :schema, 0}, type: {Ecto.Schema, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {:any, 0}, {Ecto.Changeset, :t, 2, [:any], [type: {Ecto.Changeset, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {:any, 0}, {Ecto.Multi, :operation, 13, [], [type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :tuple_set, [{2, [{:c, :tuple, [{:c, :atom, [:inspect], :unknown}, {:c, :list, {{:c, :tuple, [{:c, :atom, :any, :unknown}, :any], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}], {2, {:c, :atom, [:inspect], :unknown}}}, {:c, :tuple, [{:c, :atom, [:merge], :unknown}, {:c, :union, [:none, :none, {:c, :function, {{:c, :product, [...], ...}, {:c, :map, ...}}, :unknown}, :none, :none, :none, {:c, :tuple, [...], ...}, :none], :unknown}], {2, {:c, :atom, [:merge], :unknown}}}, {:c, :tuple, [{:c, :atom, [:put], :unknown}, :any], {2, {:c, :atom, [:put], :unknown}}}, {:c, :tuple, [{:c, :atom, [:run], :unknown}, {:c, :function, {{:c, :product, [{:c, :atom, :any, ...}, {:c, :map, ...}], :unknown}, {:c, :tuple_set, [{2, [...]}], :unknown}}, :unknown}], {2, {:c, :atom, [:run], :unknown}}}]}, {3, [{:c, :tuple, [{:c, :atom, [:changeset], :unknown}, {:c, :map, {[{{:c, :atom, [:__struct__], :unknown}, :mandatory, {:c, :atom, [Ecto.Changeset], :unknown}}, {{:c, :atom, [:action], :unknown}, :mandatory, {:c, :atom, :any, :unknown}}, {{:c, :atom, [:changes], :unknown}, :mandatory, {:c, :map, {...}, ...}}, {{:c, :atom, [:constraints], :unknown}, :mandatory, {:c, :list, ...}}, {{:c, :atom, [...], ...}, :mandatory, {:c, ...}}, {{:c, :atom, ...}, :mandatory, :any}, {{:c, ...}, :mandatory, ...}, {{...}, ...}, {...}, ...], :none, :none}, :unknown}, {:c, :list, {{:c, :tuple, [{:c, :atom, :any, :unknown}, :any], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}], {3, {:c, :atom, [:changeset], :unknown}}}, {:c, :tuple, [{:c, :atom, [:delete_all], :unknown}, {:c, :map, {[{{:c, :atom, [:__struct__], :unknown}, :mandatory, {:c, :atom, [Ecto.Query], :unknown}}, {{:c, :atom, [:aliases], :unknown}, :mandatory, :any}, {{:c, :atom, [:assocs], :unknown}, :mandatory, :any}, {{:c, :atom, [...], ...}, :mandatory, :any}, {{:c, :atom, ...}, :mandatory, :any}, {{:c, ...}, :mandatory, ...}, {{...}, ...}, {...}, ...], :none, :none}, :unknown}, {:c, :list, {{:c, :tuple, [{:c, :atom, :any, ...}, :any], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}], {3, {:c, :atom, [:delete_all], :unknown}}}, {:c, :tuple, [{:c, :atom, [:update_all], :unknown}, {:c, :map, {[{{:c, :atom, [:__struct__], :unknown}, :mandatory, {:c, :atom, [...], ...}}, {{:c, :atom, [:aliases], :unknown}, :mandatory, :any}, {{:c, :atom, [...], ...}, :mandatory, :any}, {{:c, :atom, ...}, :mandatory, :any}, {{:c, ...}, :mandatory, ...}, {{...}, ...}, {...}, ...], :none, :none}, :unknown}, {:c, :list, {{:c, :tuple, [{:c, :atom, ...}, :any], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}], {3, {:c, :atom, [:update_all], :unknown}}}]}, {4, [{:c, :tuple, [{:c, :atom, [:insert_all], :unknown}, {:c, :union, [{:c, :atom, :any, :unknown}, {:c, :binary, {8, 0}, :unknown}, :none, :none, :none, :none, {:c, :tuple, ...}, :none], :unknown}, {:c, :list, {{:c, :union, [:none, :none, :none, :none, ...], :unknown}, {:c, nil, [], :unknown}}, :unknown}, {:c, :list, {{:c, :tuple, [{:c, :atom, ...}, :any], {2, :any}}, {:c, nil, [], :unknown}}, :unknown}], {4, {:c, :atom, [:insert_all], :unknown}}}]}], :unknown}, 293}, {Ecto.Schema.Metadata, :t, 1, [], [type: {Ecto.Schema, :schema, 0}, type: {Ecto.Schema, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Changeset, :t, 1}, type: {Ecto.Changeset, :t, 0}, type: {Ecto.Multi, :operation, 0}, type: {Ecto.Multi, :operations, 0}, type: {Ecto.Multi, :t, 0}]} => {{:c, :map, {[], :any, :any}, (truncated)
:dialyzer.run error: Analysis failed with error
```