feat(update/elixir/1.18): update sentry ~> 9
Still fixing dependency compile issues

```
==> sentry
Compiling 17 files (.ex)

== Compilation error in file lib/sentry/config.ex ==
** (ArgumentError) cannot inject attribute @default_exclude_patterns into function/macro because cannot escape #Reference<0.466876627.4054974469.145395>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.18.4) lib/kernel.ex:3777: Kernel.do_at_escape/2
    (elixir 1.18.4) expanding macro: Kernel.@/1
    lib/sentry/config.ex:136: Sentry.Config.source_code_exclude_patterns/0
could not compile dependency :sentry, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile sentry --force", update it with "mix deps.update sentry" or clean it with "mix deps.clean sentry"
```