fix(update/elixir/1.18): update deprecated function `Logger.warn` => `Logger.warning`
```
: mix compile --warnings-as-errors

    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
    │
 54 │         Logger.warn("Could not download commuter rail predictions; received: #{inspect(e)}")
    │                ~
    │
    └─ lib/prediction_analyzer/predictions/download.ex:54:16: PredictionAnalyzer.Predictions.Download.get_commuter_rail_predictions/0

     warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
     │
 126 │     Logger.warn(
     │            ~
     │
     └─ lib/prediction_analyzer/predictions/download.ex:126:12: PredictionAnalyzer.Predictions.Download.handle_info/2

    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
    │
 89 │         :ok = Logger.warn(["Could not download subway vehicles. status_code=", inspect(code)])
    │                      ~
    │
    └─ lib/prediction_analyzer/vehicle_positions/tracker.ex:89:22: PredictionAnalyzer.VehiclePositions.Tracker.handle_info/2

    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
    │
 94 │         Logger.warn("Could not download subway vehicles; received: #{inspect(e)}")
    │                ~
    │
    └─ lib/prediction_analyzer/vehicle_positions/tracker.ex:94:16: PredictionAnalyzer.VehiclePositions.Tracker.handle_info/2

     warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
     │
 149 │           Logger.warn("Could not download commuter rail vehicles; received: #{inspect(e)}")
     │                  ~
     │
     └─ lib/prediction_analyzer/vehicle_positions/tracker.ex:149:18: PredictionAnalyzer.VehiclePositions.Tracker.handle_info/2

     warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
     │
 161 │     Logger.warn(
     │            ~
     │
     └─ lib/prediction_analyzer/vehicle_positions/tracker.ex:161:12: PredictionAnalyzer.VehiclePositions.Tracker.handle_info/2

     warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
     │
 179 │           Logger.warn("failed_to_parse_vehicle_entity #{inspect(e)}")
     │                  ~
     │
     └─ lib/prediction_analyzer/vehicle_positions/tracker.ex:179:18: PredictionAnalyzer.VehiclePositions.Tracker.parse_vehicles/2

    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
    │
 87 │         Logger.warn("Could not download stop names; received: #{inspect(e)}")
    │                ~
    │
    └─ lib/prediction_analyzer/stop_name_fetcher.ex:87:16: PredictionAnalyzer.StopNameFetcher.load_stop_data/1

    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
    │
 67 │       Logger.warn(
    │              ~
    │
    └─ lib/prediction_analyzer/prediction_accuracy/accuracy_tracker.ex:67:14: PredictionAnalyzer.PredictionAccuracy.AccuracyTracker.get_route_accuracy/1

    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
    │
 98 │         Logger.warn("Could not insert vehicle event: #{inspect(changeset)}")
    │                ~
    │
    └─ lib/prediction_analyzer/vehicle_positions/comparator.ex:98:16: PredictionAnalyzer.VehiclePositions.Comparator.record_arrival/1

     warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
     │
 120 │         Logger.warn("Tried to update departure time, but no arrival for #{vehicle.label}")
     │                ~
     │
     └─ lib/prediction_analyzer/vehicle_positions/comparator.ex:120:16: PredictionAnalyzer.VehiclePositions.Comparator.record_departure/1

     warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
     │
 202 │           Logger.warn(
     │                  ~
     │
     └─ lib/prediction_analyzer/vehicle_positions/comparator.ex:202:18: PredictionAnalyzer.VehiclePositions.Comparator.associate_vehicle_event_with_predictions/1

    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
    │
 38 │       Logger.warn("Prediction aggregation failed, not retrying")
    │              ~
    │
    └─ lib/prediction_analyzer/prediction_accuracy/aggregator.ex:38:14: PredictionAnalyzer.PredictionAccuracy.Aggregator.handle_info/2

     warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
     │
 108 │         Logger.warn("#{__MODULE__} do_aggregation #{inspect(e)}")
     │                ~
     │
     └─ lib/prediction_analyzer/prediction_accuracy/aggregator.ex:108:16: PredictionAnalyzer.PredictionAccuracy.Aggregator.do_aggregation/2

Compilation failed due to warnings while using the --warnings-as-errors option
```